from __future__ import annotations

from .agents import agent_extra_args, build_command, render_template
from .cli import run_command_main
from .config import (
    default_agents,
    load_config,
    merge_raw_config,
    parse_basic_toml,
    read_config_raw,
    repo_root,
    resolve_preset_path,
)
from .farm import clean_farm_args, maybe_launch_farm
from .git_safety import create_backup_branch, git_workspace_fingerprint, prune_backup_branches
from .init import write_starter_files
from .models import (
    CURRENT_LOG_POINTER_FILENAME,
    DEFAULT_COMPLETION_MARKER,
    DEFAULT_MAX_LOOPS,
    DEFAULT_MAX_TRANSIENT_RETRIES,
    DEFAULT_RETRY_NOTIFY_AFTER_SECONDS,
    DEFAULT_SEQUENCE_PROMPT_FILE,
    DEFAULT_SINGLE_PROMPT_FILE,
    DEFAULT_STOP_PATTERNS,
    DEFAULT_TIMEOUT_SECONDS,
    STREAM_READ_CHUNK_BYTES,
    TMUX_STATE_OPTION,
    TMUX_STOP_REASON_OPTION,
    VERSION,
    AgentConfig,
    AgentKind,
    CommandContext,
    CommandTemplateError,
    ConfigError,
    LoadedConfig,
    LooperConfig,
    LooperMode,
    ParsedLine,
    ProcessResult,
    PromptError,
    RunOptions,
    TmuxLayout,
)
from .process import _close_subprocess_transport, _safe_stream_write, _terminate_process_group
from .prompts import load_prompts, load_prompts_for_mode, resolve_prompt_defaults
from .retry import (
    format_byte_count,
    format_duration,
    format_loop_metrics,
    is_retryable_stop_reason,
    parse_output_line,
    retry_delay_seconds,
    retry_notification_message,
    retry_status_message,
    should_notify_retry_wait,
    transient_retry_limit_message,
    transient_retry_limit_reached,
)
from .runner import (
    apply_run_options,
    compile_completion_marker,
    compile_stop_patterns,
    make_label,
    make_run_dir,
    markdown_plan_has_unchecked_tasks,
    plan_file_all_tasks_checked,
    run_command,
    run_loop,
    run_loop_sync,
)
from .tmux import (
    current_log_pointer_path,
    display_tmux_message,
    set_tmux_window_option,
    start_tmux_log_pane,
    tmux_log_tail_command,
    transcript_renderer_command,
    update_current_log_pointer,
)
from .transcript import format_agent_log_line, split_logged_line, transcript_log_main

__all__ = [
    "CURRENT_LOG_POINTER_FILENAME",
    "DEFAULT_COMPLETION_MARKER",
    "DEFAULT_MAX_LOOPS",
    "DEFAULT_MAX_TRANSIENT_RETRIES",
    "DEFAULT_RETRY_NOTIFY_AFTER_SECONDS",
    "DEFAULT_SEQUENCE_PROMPT_FILE",
    "DEFAULT_SINGLE_PROMPT_FILE",
    "DEFAULT_STOP_PATTERNS",
    "DEFAULT_TIMEOUT_SECONDS",
    "STREAM_READ_CHUNK_BYTES",
    "TMUX_STATE_OPTION",
    "TMUX_STOP_REASON_OPTION",
    "VERSION",
    "AgentConfig",
    "AgentKind",
    "CommandContext",
    "CommandTemplateError",
    "ConfigError",
    "LoadedConfig",
    "LooperConfig",
    "LooperMode",
    "ParsedLine",
    "ProcessResult",
    "PromptError",
    "RunOptions",
    "TmuxLayout",
    "_close_subprocess_transport",
    "_safe_stream_write",
    "_terminate_process_group",
    "agent_extra_args",
    "apply_run_options",
    "build_command",
    "clean_farm_args",
    "compile_completion_marker",
    "compile_stop_patterns",
    "create_backup_branch",
    "current_log_pointer_path",
    "default_agents",
    "display_tmux_message",
    "format_agent_log_line",
    "format_byte_count",
    "format_duration",
    "format_loop_metrics",
    "git_workspace_fingerprint",
    "is_retryable_stop_reason",
    "load_config",
    "load_prompts",
    "load_prompts_for_mode",
    "make_label",
    "make_run_dir",
    "markdown_plan_has_unchecked_tasks",
    "maybe_launch_farm",
    "merge_raw_config",
    "parse_basic_toml",
    "parse_output_line",
    "plan_file_all_tasks_checked",
    "prune_backup_branches",
    "read_config_raw",
    "render_template",
    "repo_root",
    "resolve_prompt_defaults",
    "resolve_preset_path",
    "retry_delay_seconds",
    "retry_notification_message",
    "retry_status_message",
    "run_command",
    "run_command_main",
    "run_loop",
    "run_loop_sync",
    "set_tmux_window_option",
    "should_notify_retry_wait",
    "split_logged_line",
    "start_tmux_log_pane",
    "tmux_log_tail_command",
    "transcript_log_main",
    "transcript_renderer_command",
    "transient_retry_limit_message",
    "transient_retry_limit_reached",
    "update_current_log_pointer",
    "write_starter_files",
]
